# Generated by Django 4.2.3 on 2023-12-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_p_details',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='customer_skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=60)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resume.customer_p_details')),
            ],
        ),
        migrations.CreateModel(
            name='customer_project_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('durationfrom', models.DateField()),
                ('durationto', models.DateField()),
                ('projectname', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('url', models.CharField(default=None, max_length=120)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resume.customer_p_details')),
            ],
        ),
        migrations.CreateModel(
            name='customer_languages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(max_length=60)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resume.customer_p_details')),
            ],
        ),
        migrations.CreateModel(
            name='customer_intern_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('durationfrom', models.DateField()),
                ('durationto', models.DateField()),
                ('projectname', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('url', models.CharField(default=None, max_length=120)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resume.customer_p_details')),
            ],
        ),
        migrations.CreateModel(
            name='customer_e_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('year_of_passing', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('college', models.CharField(max_length=60)),
                ('college_city', models.CharField(max_length=30)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resume.customer_p_details')),
            ],
        ),
        migrations.CreateModel(
            name='customer_achievements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('achivements', models.CharField(max_length=60)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resume.customer_p_details')),
            ],
        ),
    ]
