# Generated by Django 4.2.3 on 2023-12-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_intern_details',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
