# Generated by Django 4.2.3 on 2023-12-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_customer_intern_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_project_details',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
